# Generated by Django 4.2.7 on 2023-11-29 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=50)),
                ('classification', models.CharField(choices=[('neither', 'Neither'), ('vegan', 'Vegan'), ('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], default=0, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu')),
                ('spicy', models.BooleanField(default=False)),
                ('contains_peanuts', models.BooleanField(default=True)),
                ('gluten_free', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=True)),
                ('calories', models.CharField(default=0, max_length=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu items',
                'ordering': ['category', 'name'],
            },
        ),
    ]
