# Generated by Django 4.2.7 on 2023-11-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_created_at_restaurant_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
