# Generated by Django 4.2.7 on 2023-11-02 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('token_type', models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('VERIFICATION', 'Account Verification'), ('INVITATION', 'Examiner Invitation')], max_length=100)),
                ('token', models.CharField(max_length=255)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('token_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to='user.user')),
            ],
            options={
                'verbose_name': 'VerificationToken',
                'verbose_name_plural': 'VerificationToken',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_token', models.TextField(null=True)),
                ('device_type', models.CharField(choices=[('WEB', 'WEB'), ('MOBILE', 'MOBILE'), ('IOS', 'IOS')], max_length=100, null=True)),
                ('is_safari', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='token_blacklist.outstandingtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_set', to='user.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Session',
                'ordering': ['-created_at'],
            },
        ),
    ]
