# Generated by Django 4.2.7 on 2023-11-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_item_remove_orderitem_order_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='item',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
    ]
