# Generated by Django 4.2.7 on 2023-12-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_payment_method_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
