# Generated by Django 4.2.7 on 2023-12-29 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_alter_paymentmethod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiration_month',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiration_year',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last_four_digits',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
